# Publish Grapes JS into Private Azure feed for comsumption by Omni

# YAML pipelines in a GitHub repository have CI triggers and PR triggers enabled by default
pr: none
trigger:
- dev

jobs:
- job: publishGrapesJS

  pool:
    name: 'SWT OMNI'

  steps:
  # Retain credentials
  - checkout: self
    persistCredentials: true

  # Install the node modules
  - script: npm install
    displayName: Install modules

  # Run the build operation
  - script: npm run build
    displayName: Run build

  # Run pack operation
  - script: npm pack
    displayName: Package GrapesJS

  # Commit version
  - task: PowerShell@2
    displayName: "Commit version"
    inputs:
      workingDirectory: $(Build.Repository.LocalPath)
      targetType: 'inline'
      script: |
        $version = (Get-Content package.json) | ConvertFrom-Json | Select -ExpandProperty "version"
        git config user.email "Mobius@crestron.com"
        git config user.name "Mobius"
        git add package.json package-lock.json
        git commit -m ("docs: update to version " + $version + " [skip ci]")
        git push origin HEAD:$(Build.SourceBranch)


  # Publish the type defs to the feed
  - task: Npm@1
    inputs:
      command: 'publish'
      publishRegistry: 'useFeed'
       # Below value is generated by Azure pipelines and is only a target registry for the feed
      publishFeed: 'bb29ef81-3bfb-4785-b394-480dbae4b826/91b7f8d3-968d-462a-b960-e76ff11d81c5'